### ISSUE TITLE
Migrating to a different underlying library

### ISSUE THREAD

**Issue by glvr182** [awesome-gocui/gocui#42]
Just gonna throw it out here, Termbox-Go is no longer maintained by NSF as we probably all know.
This made me wonder if it might be time for us to switch to a different library.

For example TCell. In #41 we discussed briefly about the Shift-Enter problem and how we could fix this. This keybind would be possible with TCell.

Hope to get feedback on this thought

**Comment by mjarkk** [comment]
To further improve this fork this would be a welcome change for a lot of end user i think because we are stopped now by a lot of limitations of termbox,  

Beside that if we have a better and maintained tui library under our fork means that we are further prove but on the other hand we might change the core functionality so much that it won't be gocui anymore.  

If the core functionality changes only a small bit or nothing at all and if we all agree that the library would make gocui better in the long term i'm fine with this change.

**Comment by abitrolly** [comment]
It would be really nice to get a list of all current problems with `termbox` somewhere.

**Comment by mjarkk** [comment]
Totally agree but i need to find some time to dig through issues.

**Comment by mjarkk** [comment]
Yay we can finally close this issue!!
